### PR TITLE
I had to change these lines to support earlier versions of python(3.5)

### PR DESCRIPTION
**Pull request by Ren22**

### CODE REVIEW

**Comment by intsco** [comment]
@Ren22 please add PRs to the corresponding project

**Comment by Ren22** [comment]
@intsco added it to this PR https://github.com/metaspace2020/metaspace/pull/142

**Comment by Ren22** [comment]
@intsco should I changed the branch for merging from `master` to `release/v1.0` as well?

**Comment by intsco** [comment]
If we merge these changes only to master they won't be deployed to prod for a while. If it's a hotfix then it should go into the release branch.

**Comment by Ren22** [comment]
It's not a hotfix and should be fine with `master`, merging and closing

**Pull request merged**
