### PR TITLE
Fix sm-api

### PR DESCRIPTION
**Pull request by LachlanStuart**
Due to the `bootstrap_and_run` refactoring, the global `logger` wasn't defined, causing most API endpoints to have errors. My solution isn't very elegant - suggestions welcome.

Also, I included a change to `r1_5_20190829_update_moldb_names.py`, because Black kept reformatting this file.

### CODE REVIEW

**Comment by intsco** [comment]
@LachlanStuart Sorry, I fix that in the `feature/python-linter` branch. I can cherry-pick that commit to this branch

**Comment by LachlanStuart** [comment]
@intsco Up to you. If `feature/python-linter` isn't too far away, I can just wait for that. I don't need it locally as I don't reprocess often, but I needed to add this for deployment to staging

**Comment by intsco** [comment]
@LachlanStuart `feature/python-linter` is a bit far away. So I'll add the fix to this branch

**Comment by intsco** [comment]
@LachlanStuart please review the last commit :)

**Comment by LachlanStuart** [comment]
@intsco Looks good to me. I can't hit approve though since I made the PR.

**Pull request merged**
